# Generated by Django 3.2.11 on 2022-09-13 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivado', models.BooleanField(default=False)),
                ('data', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('A Confirmar', 'A Confirmar'), ('Confirmado', 'Confirmado'), ('Finalizado', 'Finalizado')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.person')),
            ],
            options={
                'db_table': 'agendamentos',
            },
        ),
    ]
